name: i-rochiño
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: [vendor] #Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
gems:
  - jekyll-sitemap
collections:
  som:
    output : true
    permalink : /som/:path/
  montaxe:
    output : true
    permalink : /montaxe/:path/
  planificar:
    output : true
    permalink : /planificar/:path/
  memoria:
    output : true
    permalink : /memoria/:path/
