name: i-rochiño
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  som:
    output : true
    permalink : /som/:path/
  montaxe:
    output : true
    permalink : /montaxe/:path/
gems:
  - jekyll-sitemap
